/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTopologiRouteImport } from './routes/_authenticated/topologi'
import { Route as AuthenticatedOltRouteImport } from './routes/_authenticated/olt'
import { Route as AuthenticatedOdpRouteImport } from './routes/_authenticated/odp'
import { Route as AuthenticatedOdcRouteImport } from './routes/_authenticated/odc'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopologiRoute = AuthenticatedTopologiRouteImport.update({
  id: '/topologi',
  path: '/topologi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOltRoute = AuthenticatedOltRouteImport.update({
  id: '/olt',
  path: '/olt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOdpRoute = AuthenticatedOdpRouteImport.update({
  id: '/odp',
  path: '/odp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOdcRoute = AuthenticatedOdcRouteImport.update({
  id: '/odc',
  path: '/odc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/odc': typeof AuthenticatedOdcRoute
  '/odp': typeof AuthenticatedOdpRoute
  '/olt': typeof AuthenticatedOltRoute
  '/topologi': typeof AuthenticatedTopologiRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/odc': typeof AuthenticatedOdcRoute
  '/odp': typeof AuthenticatedOdpRoute
  '/olt': typeof AuthenticatedOltRoute
  '/topologi': typeof AuthenticatedTopologiRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/odc': typeof AuthenticatedOdcRoute
  '/_authenticated/odp': typeof AuthenticatedOdpRoute
  '/_authenticated/olt': typeof AuthenticatedOltRoute
  '/_authenticated/topologi': typeof AuthenticatedTopologiRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/laporan'
    | '/odc'
    | '/odp'
    | '/olt'
    | '/topologi'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/laporan'
    | '/odc'
    | '/odp'
    | '/olt'
    | '/topologi'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/laporan'
    | '/_authenticated/odc'
    | '/_authenticated/odp'
    | '/_authenticated/olt'
    | '/_authenticated/topologi'
    | '/_authenticated/users'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topologi': {
      id: '/_authenticated/topologi'
      path: '/topologi'
      fullPath: '/topologi'
      preLoaderRoute: typeof AuthenticatedTopologiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/olt': {
      id: '/_authenticated/olt'
      path: '/olt'
      fullPath: '/olt'
      preLoaderRoute: typeof AuthenticatedOltRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/odp': {
      id: '/_authenticated/odp'
      path: '/odp'
      fullPath: '/odp'
      preLoaderRoute: typeof AuthenticatedOdpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/odc': {
      id: '/_authenticated/odc'
      path: '/odc'
      fullPath: '/odc'
      preLoaderRoute: typeof AuthenticatedOdcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedOdcRoute: typeof AuthenticatedOdcRoute
  AuthenticatedOdpRoute: typeof AuthenticatedOdpRoute
  AuthenticatedOltRoute: typeof AuthenticatedOltRoute
  AuthenticatedTopologiRoute: typeof AuthenticatedTopologiRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedOdcRoute: AuthenticatedOdcRoute,
  AuthenticatedOdpRoute: AuthenticatedOdpRoute,
  AuthenticatedOltRoute: AuthenticatedOltRoute,
  AuthenticatedTopologiRoute: AuthenticatedTopologiRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
